[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0", "libgl1-mesa-glx"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "pip uninstall -y opencv-python",
  "pip install opencv-python-headless==4.8.1.78"
]


[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

